[global/wm]
include-file=~/.config/polybar/colors.ini
include-file=~/.config/polybar/utils.ini
include-file=~/.config/polybar/network.ini
include-file=~/.config/polybar/system.ini
include-file=~/.config/polybar/gpu.ini
include-file=~/.config/polybar/cpu.ini


[bar-base]
type = bar
width = 100%
height = 1.8%
radius = 0
dpi-x = 96
dpi-y = 96
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 1pt
border-size = 6pt
border-color = ${colors.background}
offset-y = 0.0%
offset-x = 0%
padding-left = 0
padding-right = 0
module-margin = 0
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
wm-restack = awesome
override-redirect = true
fixed-center = true

; Main.
font-0 = JetBrainsMono Nerd Font:pixelsize=13:weight=bold;4
; Main half circle separators.
font-1 = JetBrainsMono Nerd Font:pixelsize=19;4
; Logo
font-2 = JetBrainsMono Nerd Font:pixelsize=23:weight=bold;5
; Spaces.
font-3 = JetBrainsMono Nerd Font:pixelsize=6
; For mod sep.
font-4 = JetBrainsMono Nerd Font:pixelsize=15:antialias=false;4
; For workspaces
font-5 = JetBrainsMono Nerd Font:pixelsize=17:antialias=true;5

; [bar/top]
; inherit = bar-base
; bottom = false
; modules-left = space-small os space-small left time space-alt date right space space-small nix space-small ethernet
; modules-center = workspaces
; modules-right = tray space space-small left storage space-small-alt space-small-alt volume right space space wlan ethernet dunst space-small

[bar/top]
inherit = bar-base
bottom = false
modules-left = space left space-alt cpu-usage space-alt mod-sep space-alt cpu-memory space-alt right space space sep space space cpu-temperature
; space space space cpu-power
modules-center = left space-alt time space-alt mod-sep space-alt space-alt mod-sep space-alt date space-alt right
modules-right = gpu-temp space space sep space space left space-alt gpu-memory space-alt mod-sep space-alt gpu-usage space-alt right space
; gpu-power space space space

[bar/bottom]
inherit = bar-base
monitor = DP-2
bottom = true
; modules-left = space left fail2ban ufw mod-sep space-alt wlan space-alt right space space sep space space downspeed space space space upspeed
modules-left = space left ufw mod-sep space-alt ethernet space-alt right space space sep space space downspeed space space space upspeed
modules-center= workspaces-primary
modules-right = tray space space sep space space space space space space space sep space space left space-alt volume space-alt right space

[bar/bottom-secondary]
inherit = bar-base
monitor = DP-5
bottom = true
height = 2.2%
; modules-left = space left fail2ban ufw mod-sep space-alt wlan space-alt right space space sep space space downspeed space space space upspeed
modules-left =
modules-center= workspaces-secondary
modules-right = left space-alt time space-alt mod-sep space-alt space-alt mod-sep space-alt date space-alt right

[bar/bottom-tertiary]
inherit = bar-base
monitor = HDMI-0
bottom = true
height = 1%
modules-left =
modules-center= workspaces-tertiary
modules-right = left space-alt time space-alt mod-sep space-alt space-alt mod-sep space-alt date space-alt right



[settings]
screenchange-reload = true
pseudo-transparency = true

[module/workspaces-primary]
type = custom/script
exec = ~/.config/polybar/scripts/workspaces.sh DP-2
tail = true

[module/workspaces-secondary]
type = custom/script
exec = ~/.config/polybar/scripts/workspaces.sh DP-5
tail = true

[module/workspaces-tertiary]
type = custom/script
exec = ~/.config/polybar/scripts/workspaces.sh HDMI-0
tail = true

[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true

icon-0="0;"
icon-1="1;"
icon-2="2;"
icon-3="3;"
icon-4="4;"
icon-5="5; "
icon-default=""

; Active.
label-active = " %icon%"
label-active-foreground = ${colors.foreground}
label-active-background = ${colors.background}
label-active-font = 6
; Occupied.
label-occupied = " %icon%"
label-occupied-foreground = ${colors.foreground}
label-occupied-background = ${colors.background}
label-occupied-font = 6
; Empty.
label-empty = " %icon%"
label-empty-foreground = ${colors.foreground}
label-empty-background = ${colors.background}
label-empty-font = 6
; Urgent.
label-urgent = " %icon%"
label-urgent-foreground = ${colors.orange}
label-urgent-background = ${colors.background}
label-urgent-font = 6